openapi: 3.0.0
info:
  version: 0.0.1
  title: Orders
  description: Orders
  termsOfService: terms
servers:
  - url: 'http://127.0.0.1:9999'
    description: 'Optional server description, e.g. Main (production) server'
paths:
  /order/{orderId}:
    get:
      summary: Get Order
      description: Get Order
      operationId: getOrder
      parameters:
        - name: orderId
          in: path
          required: true
          description: Order ID
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: The specified user ID is invalid (not a number).
        '404':
          description: A user with the specified ID was not found.
        default:
          description: Unexpected error
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          description: id
        name:
          type: string
          description: name